# Generated by Django 4.2.10 on 2024-02-28 18:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('ticket_id', models.CharField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator('^\\d{8,15}$', message='Enter a valid Id.')])),
                ('trip_id', models.CharField(max_length=15, unique=True)),
                ('traveller_name', models.CharField(max_length=255)),
                ('traveller_Phone_no', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', message='Enter a valid phone number.')])),
                ('ticket_cost', models.FloatField()),
                ('traveller_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')])),
            ],
        ),
    ]
