# Generated by Django 4.2.10 on 2024-02-28 19:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('route', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.CharField(max_length=15, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{8,15}$', message='Enter a minimum 8 digit')])),
                ('vehicle_id', models.CharField(max_length=255)),
                ('driver_name', models.CharField(max_length=255)),
                ('trip_distance', models.FloatField()),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_as_route', to='route.route')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_as_user', to='route.route')),
            ],
        ),
    ]
