# Generated by Django 4.2.10 on 2024-02-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='user_id',
            field=models.CharField(verbose_name='<django.db.models.query_utils.DeferredAttribute object at 0x00000184A4AD94C0>'),
        ),
    ]
