# Generated by Django 4.2.10 on 2024-02-29 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
        ('trip', '0003_alter_trip_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.route', to_field='user_id'),
        ),
    ]
